// ticketing-angular-admin/src/app/events/form/edit/edit-event.component.ts
// create-event.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { AppService, Events, TicketType } from '../../../app.service';

@Component({
  selector: 'app-edit-event',
  templateUrl: './edit-event.component.html',
  styleUrls: ['./edit-event.component.scss'],
})
export class EditEventComponent implements OnInit {
  eventId: number;
  newEvent : Events;
  ticketTypes: Array<TicketType> = [{ name: '', price: '', available_quantity: 0 }];
  categories: Array<any> = [];
  imageUrl: string;
  filename: string;
  errorMessage: string;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private http: HttpClient,
    private dataService: AppService
  ) {}

  ngOnInit(): void {
    this.eventId = Number(this.route.snapshot.paramMap.get('id'));
    if (this.eventId) {
      this.loadEventData(this.eventId);
    }
    this.getCategories();
  }

  loadEventData(id: number): void {
    try {
      this.dataService.getEventById(id).subscribe(
        (data: any) => {
          this.newEvent = data.data;
          console.log(this.newEvent)
          this.ticketTypes = data.data.ticket_types || [];
          this.imageUrl = data.data.image_banner || null;
        },

      );
    } catch (error) {
      console.error('Error loading event:', error);
    }

  }

  getCategories() {
    try {
      this.dataService.getListCategories().subscribe((data: any) => {
        this.categories = data.data;
      });
    } catch (error) {
      console.log(error);
    }
  }

  addTicketType() {
    this.ticketTypes.push({ name: '', price: '', available_quantity: 0 });
  }

  removeTicketType(index: number) {
    this.ticketTypes.splice(index, 1);
  }

  // create-event.component.ts

  handleFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files ? input.files[0] : null;

    if (file) {
      const maxSize = 2 * 1024 * 1024; // 2MB size limit
      if (file.size > maxSize) {
        this.errorMessage = 'File size exceeds 2MB';
        this.filename = '';
        this.imageUrl = '';
        return;
      }

      const reader = new FileReader();
      reader.onload = () => {
        this.imageUrl = reader.result as string; // Set the preview URL
        this.filename = file.name;
        this.errorMessage = '';
      };
      reader.readAsDataURL(file); // Read the file as a data URL
    }
  }

  handleSubmit() {
    const formData = new FormData();
    formData.append('name', this.newEvent.name);
    formData.append('start_datetime', this.newEvent.start_datetime);
    formData.append('end_datetime', this.newEvent.end_datetime);
    formData.append('location', this.newEvent.location);
    formData.append('description', this.newEvent.description);
    formData.append('ticket_types', JSON.stringify(this.ticketTypes));

    const uploadInput = document.querySelector('input[type="file"]') as HTMLInputElement;
    if (uploadInput.files && uploadInput.files.length > 0) {
        formData.append('image_banner', uploadInput.files[0]);
    }else {
      formData.append('image_banner', this.newEvent.image_banner);
    }

    this.dataService.updateEvent(this.eventId, formData).subscribe(
        () => {
            this.router.navigate(['/events']);
        },
        (error) => {
            console.error('Error updating event:', error);
        }
    );
}

}

<!-- create-event.component.html -->
<form (ngSubmit)="handleSubmit()" class="space-y-4 py-4">
  <!-- Event Details Section -->
  <h2 class="text-2xl font-bold mb-4">Create an Event</h2>

  <!-- Event Name -->
  <div class="mb-3">
    <label for="name" class="font-medium">Event name*</label>
    <input
      [(ngModel)]="newEvent.name"
      type="text"
      id="name"
      placeholder="Event name"
      required
      class="form-input w-full border rounded-md h-10 px-2"
      name="name"
    />
  </div>

  <!-- Category -->
  <!-- <div class="mb-3">
    <label for="category" class="font-medium">Category*</label>
    <select
      [(ngModel)]="newEvent.category"
      id="category"
      required
      class="form-input w-full border rounded-md h-10 px-2"
      name="category"
    >
      <option value="">Select category</option>
      <option *ngFor="let category of categories" [value]="category.id">{{ category.name }}</option>
    </select>
  </div> -->

  <!-- Start Date and End Date -->
  <div class="flex space-x-2 mb-3">
    <div class="flex-1">
      <label for="start_datetime" class="font-medium">Start date*</label>
      <input
        [(ngModel)]="newEvent.start_datetime"
        type="datetime-local"
        id="start_datetime"
        required
        class="form-input w-full border rounded-md h-10 px-2"
        name="start_datetime"
      />
    </div>
    <div class="flex-1">
      <label for="end_datetime" class="font-medium">End date*</label>
      <input
        [(ngModel)]="newEvent.end_datetime"
        type="datetime-local"
        id="end_datetime"
        required
        class="form-input w-full border rounded-md h-10 px-2"
        name="end_datetime"
      />
    </div>
  </div>

  <!-- Location -->
  <div class="mb-3">
    <label for="location" class="font-medium">Location*</label>
    <input
      [(ngModel)]="newEvent.location"
      type="text"
      id="location"
      placeholder="Venue or URL"
      required
      class="form-input w-full border rounded-md h-10 px-2"
      name="location"
    />
  </div>

  <!-- Description -->
  <div class="mb-3">
    <label for="description" class="font-medium">Description*</label>
    <textarea
      [(ngModel)]="newEvent.description"
      id="description"
      placeholder="Enter description"
      required
      class="form-input w-full border rounded-md px-2 py-1"
      name="description"
    ></textarea>
  </div>

  <!-- Ticket Types Section -->
  <h3 class="text-lg font-bold mb-2">Ticket Types</h3>
  <div *ngFor="let ticket of ticketTypes; let i = index" class="space-y-2 mb-3 border-b pb-3">
    <div>
      <label class="font-medium">Ticket name*</label>
      <input
        [(ngModel)]="ticket.name"
        placeholder="Ticket name"
        class="form-input w-full border rounded-md h-10 px-2"
        name="ticketName-{{ i }}"
      />
    </div>
    <div>
      <label class="font-medium">Price*</label>
      <input
        [(ngModel)]="ticket.price"
        type="number"
        placeholder="Price"
        class="form-input w-full border rounded-md h-10 px-2"
        name="ticketPrice-{{ i }}"
      />
    </div>
    <div>
      <label class="font-medium">Quantity*</label>
      <input
        [(ngModel)]="ticket.available_quantity"
        type="number"
        placeholder="Quantity"
        class="form-input w-full border rounded-md h-10 px-2"
        name="ticketQuantity-{{ i }}"
      />
    </div>
    <button type="button" (click)="removeTicketType(i)" class="text-red-600 hover:underline">Remove</button>
  </div>
  <button type="button" (click)="addTicketType()" class="bg-blue-600 text-white px-3 py-2 rounded-md">
    Add Ticket Type
  </button>

  <!-- Image Banner Section -->
  <h3 class="text-lg font-bold mb-2">Image Banner</h3>
  <div class="mb-6 text-center">
    <input type="file" accept="image/*" (change)="handleFileChange($event)" class="cursor-pointer" />
    <span *ngIf="filename" class="text-gray-500">{{ filename }}</span>
    <img *ngIf="imageUrl" [src]="imageUrl" class="w-full h-auto mt-4" alt="Image preview" />
  </div>

  <button type="submit" class="bg-blue-600 text-white w-full px-4 py-2 rounded-md">Update Event</button>
</form>

// ticketing-vue/src/views/form/EditEvent.vue
<template>
    <loading :isLoading="isLoading" />
    <form @submit.prevent="handleSubmit" class="space-y-6 py-4">
        <!-- Event Details Section -->
        <div class="px-4 md:px-8 flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-6">
            <!-- Main Content -->
            <div class="flex-1">
                <h2 class="text-[#0d141c] text-2xl font-bold leading-tight mb-6">Edit Event</h2>

                <!-- Event Name -->
                <div class="flex flex-col space-y-4 mb-4">
                    <label for="name" class="text-[#0d141c] text-base font-medium">Event name*</label>
                    <input v-model="newEvent.name" type="text" id="name" placeholder="Enter event name" required
                        class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                    <p v-if="eventNameTooLong" class="text-red-500 text-sm">Event name cannot exceed 30 characters.</p>
                </div>

                <!-- Category -->
                <div class="flex flex-col space-y-4 mb-4">
                    <label for="category" class="text-[#0d141c] text-base font-medium">Category*</label>
                    <select v-model="newEvent.category" id="category" required
                        class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 bg-[image:--select-button-svg] placeholder:text-[#49719c]">
                        <option value="">Select category</option>
                        <option class="rounded-lg" v-for="category in categories" :key="category.id" :value="category.id">
                            {{ category.name }}
                        </option>
                    </select>
                </div>

                <!-- Start Date and End Date -->
                <div class="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-4 mb-4">
                    <div class="flex-1">
                        <label for="start_datetime" class="text-[#0d141c] text-base font-medium">Start date*</label>
                        <input v-model="newEvent.start_datetime" type="datetime-local" id="start_datetime" required
                            class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                    </div>
                    <div class="flex-1">
                        <label for="end_datetime" class="text-[#0d141c] text-base font-medium">End date*</label>
                        <input v-model="newEvent.end_datetime" type="datetime-local" id="end_datetime" required
                            class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                    </div>
                </div>

                <!-- Location -->
                <div class="flex flex-col space-y-4 mb-4">
                    <label for="location" class="text-[#0d141c] text-base font-medium">Location (Venue or Online
                        URL)*</label>
                    <input v-model="newEvent.location" type="text" id="location" placeholder="Enter location" required
                        class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                </div>

                <!-- Description -->
                <div class="flex flex-col space-y-4 mb-4">
                    <label for="description" class="text-[#0d141c] text-base font-medium">Description*</label>
                    <textarea v-model="newEvent.description" id="description" placeholder="Enter description" required
                        class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] min-h-36 px-4 py-2 placeholder:text-[#49719c]"></textarea>
                </div>
            </div>

            <!-- Ticket Types Section -->
            <div class="flex-1">
                <h3 class="text-[#0d141c] text-lg font-bold leading-tight mb-4">Ticket Types</h3>
                <div v-for="(ticket, index) in ticketTypes" :key="index" class="flex flex-col space-y-4 mb-4">
                    <div class="flex flex-col space-y-4">
                        <label class="text-[#0d141c] text-base font-medium">Ticket name*</label>
                        <input v-model="ticket.name" placeholder="Enter ticket name"
                            class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                    </div>
                    <div class="flex flex-col space-y-4">
                        <label class="text-[#0d141c] text-base font-medium">Price*</label>
                        <input v-model="ticket.price" placeholder="Enter price" type="number"
                            class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                    </div>
                    <div class="flex flex-col space-y-4">
                        <label class="text-[#0d141c] text-base font-medium">Quantity*</label>
                        <input v-model="ticket.available_quantity" placeholder="Enter quantity" type="number"
                            class="form-input w-full border border-[#cedbe8] rounded-xl bg-slate-50 text-[#0d141c] h-14 px-4 py-2 placeholder:text-[#49719c]" />
                    </div>
                    <button type="button" @click="removeTicketType(index)" class="text-red-600 hover:underline">
                        Remove
                    </button>
                </div>
                <button type="button" @click="addTicketType" class="bg-[#007bff] text-white px-4 py-2 rounded-xl">
                    Add Ticket Type
                </button>
            </div>
        </div>

        <!-- Image Banner Section -->
        <div class="px-4 md:px-8 mt-6 flex flex-col items-center justify-center">
            <label class="flex flex-col space-y-4 items-center justify-center mb-16">
                <p class="text-[#0d141c] text-base font-medium">Image Banner*</p>
                <p v-if="errorMessage" class="text-red-500">{{ errorMessage }}</p>
                <div
                    class="max-w-sm mx-auto bg-white border-dashed border-2 border-gray-400 rounded-lg p-6 text-center">
                    <input ref="uploadInput" id="upload" type="file" class="hidden" accept="image/*"
                        @change="handleFileChange" />
                    <label for="upload" class="cursor-pointer">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-8 h-8 text-gray-700 mx-auto mb-4">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
                        </svg>
                        <h5 class="text-xl font-bold text-gray-700 mb-2">Upload Picture</h5>
                        <p class="text-sm text-gray-400">Choose photo size should be less than <b
                                class="text-gray-600">2MB</b></p>
                        <p class="text-sm text-gray-400">and should be in <b class="text-gray-600">JPG, PNG, or GIF</b>
                            format.</p>
                        <span id="filename" class="text-gray-500 bg-gray-200 z-50">{{ filename }}</span>
                    </label>
                    <img v-if="imageUrl" :src="imageUrl" class="w-full h-auto mt-4" alt="Image preview" />
                </div>
            </label>

            <!-- Submit Button -->
            <div class="w-full">
                <button type="submit"
                    :disabled="eventNameTooLong"
                    class="bg-[#2589f4] text-slate-50 w-full px-5 py-3 rounded-xl text-base font-bold hover:bg-[#1a6bd8]">
                    Update
                </button>
            </div>
        </div>
    </form>
</template>

<script>
import { ref, onMounted, reactive, toRefs, defineAsyncComponent, computed } from 'vue';
import { useRoute } from 'vue-router';
import apiClient from '@/helpers/axios';
import router from '@/router';
import { useToast } from 'vue-toastification';
const Loading = defineAsyncComponent(() => import('@/components/Loading.vue'));

export default {
    name: 'UpdateEvent',
    components: {
        Loading
    },
    setup() {
        const route = useRoute();
        const eventId = route.params.id; // Get event ID from path
        const state = reactive({
            newEvent: {
                name: '',
                description: '',
                start_datetime: '',
                end_datetime: '',
                location: '',
            },
            ticketTypes: [],
            imageUrl: null,
            filename: '',
            isLoading: false,
            errorMessage: '',
            categories: [],
        });

        const toast = useToast();
        const { newEvent, ticketTypes, imageUrl, filename, isLoading, errorMessage } = toRefs(state);

        const addTicketType = () => {
            ticketTypes.value.push({ name: '', price: '', available_quantity: '' });
        };

        const removeTicketType = (index) => {
            ticketTypes.value.splice(index, 1);
        };

        const handleFileChange = (event) => {
            const file = event.target.files[0];
            if (file) {
                const maxSize = 2 * 1024 * 1024; // 2MB
                if (file.size > maxSize) {
                    errorMessage.value = 'File size exceeds 2MB';
                    return;
                }
                const reader = new FileReader();
                reader.onload = () => {
                    imageUrl.value = reader.result;
                    filename.value = file.name;
                    errorMessage.value = '';
                };
                reader.readAsDataURL(file);
            }
        };

        const getCategories = async () => {
            try {
                const response = await apiClient.get('/api/categories/list');
                state.categories = response.data;
            } catch (error) {
                console.error('Error fetching categories:', error);
            }
        };

        const fetchEventDetails = async () => {
            if (!eventId) return;
            try {
                const response = await apiClient.get(`/api/events/${eventId}`);
                const eventData = response.data;
                // Populate event details
                state.newEvent.name = eventData.name;
                state.newEvent.description = eventData.description;
                state.newEvent.start_datetime = eventData.start_datetime;
                state.newEvent.end_datetime = eventData.end_datetime;
                state.newEvent.location = eventData.location;
                // Populate ticket types
                state.ticketTypes = eventData.ticket_types.map(ticket => ({
                    id: ticket.id,
                    name: ticket.name,
                    price: ticket.price,
                    available_quantity: ticket.available_quantity
                }));

                // Set image banner URL
                state.imageUrl = eventData.image_banner;
            } catch (error) {
                console.log('error.status ', error.status)
                if (error.status === 404) {
                    toast.error('Event not found')
                    router.push('/my_events')
                }
                console.error('Error fetching event details:', error);
            }
        };

        const handleSubmit = async () => {
            state.isLoading = true;
            try {
                const formData = new FormData();
                for (const key in newEvent.value) {
                    formData.append(key, newEvent.value[key]);
                }
                formData.append('ticket_types', JSON.stringify(ticketTypes.value));
                const uploadInput = document.getElementById('upload');
                if (uploadInput.files.length > 0) {
                    formData.append('image_banner', uploadInput.files[0]);
                }

                if (eventId) {
                    await apiClient.put(`/api/events/${eventId}`, formData, {
                        headers: {
                            'Content-Type': 'multipart/form-data'
                        }
                    });
                    toast.success('Event updated successfully');
                } else {
                    await apiClient.post('/api/events', formData, {
                        headers: {
                            'Content-Type': 'multipart/form-data'
                        }
                    });
                    toast.success('Event created successfully');
                }

                router.push('/all-for-you');
            } catch (error) {
                console.error('Error creating or updating event:', error);
                toast.error('Failed to save event');
            } finally {
                state.isLoading = false;
            }
        };

        const eventNameTooLong = computed(() => state.newEvent.name.length > 30);

        onMounted(() => {
            addTicketType();
            getCategories();
            fetchEventDetails();
        });

        return {
            ...toRefs(state),
            newEvent,
            ticketTypes,
            imageUrl,
            filename,
            isLoading,
            errorMessage,
            addTicketType,
            removeTicketType,
            handleFileChange,
            handleSubmit,
            eventNameTooLong,
        };
    }
};
</script>
